#!/bin/bash
trap ctrl_c INT
ctrl_c(){
iplatam="186.$((10 + RANDOM % 100)).$((10 + RANDOM % 100)).$((10 + RANDOM % 100))"
curl -s "https://ipapi.co/$iplatam/json" -o ip.txt
geo=$(cat ip.txt | grep "country_name" | tr ',""' " " | awk '{print $3 $4}')
echo -e "\e[1;35mip/country: $iplatam $geo last generated ip ago \e[2m$date\e[0m"
rm ip.txt > /dev/null 2>&1
read
exit
}
loading(){
spin[0]="\e[1;35m-"
spin[1]="\\"
spin[2]="|"
spin[3]="/"
spin[4]="-"
spin[5]="\\"
spin[6]="|"
spin[7]="/"
spin[8]="-"
spin[9]="\\"
spin[10]="|"
spin[11]="/"
spin[12]="-"
spin[13]="\\"
spin[14]="|"
spin[15]="/"
spin[16]="-"
spin[17]="\\"
spin[18]="|"
spin[19]="/"
spin[20]="\e[1;34mloaded\e[0m"
echo -en "$1 ${spin[0]}"
for i in "${spin[@]}"
do
echo -ne "\b$i"
sleep 0.1
done
}

loading "\e[0mlatin america ip generator"
echo # space
while :;
do
date=$(date | awk '{print $4}')
iplatam="186.$((10 + RANDOM % 100)).$((10 + RANDOM % 100)).$((10 + RANDOM % 100))"
curl -s "https://ipapi.co/$iplatam/json" -o ip.txt
geo=$(cat ip.txt | grep "country_name" | tr ',""' " " | awk '{print $3 $4}') 
echo -e "\e[0m\e[2mip/country:\e[0m $iplatam\e[0m $geo \e[2mtime:\e[0m $date "
rm ip.txt > /dev/null 2>&1
done 


